---
title: "sigma"
output: html_document
date: "2025-02-07"
---

```{r, echo=F}
knitr::opts_chunk$set(echo = F, message = F)
```


```{r, message = F, warning = F}
# load packages outside of simulation
library(papaja)
library(patchwork)
#source required functions & parameters
source('../../../R/functions.R')
source('../../../R/parameters.R')
```

```{r}
# load results
resultsSVNP_hyper <- read_rds("../../../output/resultsSVNP_hyper.RDS")%>% 
    mutate(N = ifelse(N == 100, "N = 100", "N = 200"),
         `Cross Loading` = as.character(cross)) 

convSVNP_hyper <- read_rds("../../../output/convSVNP_hyper.RDS")


```

```{r}
resultsSVNP_hyper <- 
  resultsSVNP_hyper %>% 
  group_by(N, `Cross Loading`, iteration) %>% 
  mutate(
         biasCrossMean_1 = abs(crossEstMean_1 - cross),
         biasCrossMean_2 = abs(crossEstMean_2 - 0),
         biasCrossMean_3 = abs(crossEstMean_3 - 0),
         biasCrossMean_4 = abs(crossEstMean_4 - 0),
         biasCrossMean_5 = abs(crossEstMean_5 - 0),
         biasCrossMean_6 = abs(crossEstMean_6 - cross),
         SigmaEstMean = SigmaEstMean,
         SigmaEstMed = SigmaEstMed,
         SigmaSquEstMean = SigmaEstMean^2,
         SigmaSquEstMed = SigmaEstMed^2
         ) 
  
```

# summarise mean sigmaSqu per condtion
```{r}
resultsSVNP_hyper %>% 
  group_by(N, `Cross Loading` )%>% 
  summarise(`Mean Mean Estimate` = mean(SigmaSquEstMean),
           `Mean Median Estimate`  = mean(SigmaSquEstMed)) %>% 
  mutate(across(
    where(is.numeric), 
    ~ round(., 3)
    )
  )

# write output for table 
write_rds(resultsSVNP_hyper, "../../figures/sigmaSqu_per_cond.RDS")
```
# histogram distribution sigma 


## mean est
```{r}
library(ggplot2)
library(dplyr)
library(glue)

hist_est_sigma2 <- 
resultsSVNP_hyper %>%
  mutate(`Cross Loading` = glue("Cross Loading = {`Cross Loading`}")) %>%
  group_by(N, `Cross Loading`) %>%
  mutate(mean_SigmaSquEstMean = mean(SigmaSquEstMean, na.rm = TRUE)) %>%
  ggplot(mapping = aes(x = SigmaSquEstMean)) +
  geom_histogram() +
  geom_vline(aes(xintercept = mean_SigmaSquEstMean), color = "red", linetype = "dashed") +
  facet_wrap(N ~ `Cross Loading`,  scales = "fixed") +
  theme_apa() +
  labs(
    x = " \u03c3\u00B2 (mean estimate)",
    title = "Distribution of \u03c3\u00B2 in SVNP: \u03c3 ~ Cauchy(0 , 1) across population conditions"
  )

```

```{r}
saveRDS(hist_est_sigma2, file = "../../figures/hist_meanest_sigmasqu.RDS")
```

# plot bias against Sigma: 

## cross-loading 1

```{r}
cross_1_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasCrossMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
cross_1_sigmabias
```

## cross loading 6
```{r}
cross6_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasCrossMean_6))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
cross6_sigmabias
```

## cross-loading 2-5

```{r}
cross2_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasCrossMean_2))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
cross2_sigmabias
```


```{r}
cross3_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasCrossMean_3))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
cross3_sigmabias
```

```{r}
cross4_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasCrossMean_4))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
cross4_sigmabias
```

```{r}
cross5_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasCrossMean_4))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
cross5_sigmabias
```
## main loading 1, 2, 5, 6


```{r}
main1_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasMainMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
main1_sigmabias
```

```{r}
main2_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasMainMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
main2_sigmabias
```
```{r}
main5_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasMainMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
main5_sigmabias
```

```{r}
main6_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasMainMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
main6_sigmabias
```

##  main loading 3 & 4

```{r}
main3_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasMainMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
main3_sigmabias
```

```{r}
main4_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasMainMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
main4_sigmabias
```

## factor corr

```{r}
factcorr_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasFactCorrMean))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
factcorr_sigmabias
```

## residual variances 1-6

```{r}
theta1_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasThetaMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
theta1_sigmabias
```

```{r}
theta2_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasThetaMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
theta2_sigmabias
```

```{r}
theta3_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasThetaMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
theta3_sigmabias
```

```{r}
theta4_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasThetaMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
theta4_sigmabias
```

```{r}
theta5_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasThetaMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
theta5_sigmabias
```
```{r}
theta6_sigmabias <- 
resultsSVNP_hyper %>% 
  ggplot(mapping = aes(x = SigmaSquEstMean, y = biasThetaMean_1))+
  geom_point(size = .3)+
  facet_wrap(N~`Cross Loading`)+
  theme_apa()
theta6_sigmabias
```

